set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",xterm-256color:RGB"

set -g status-style 'bg=colour023,fg=colour250'
set -g window-status-current-style 'bg=colour029,fg=colour255'

set -g mouse on
bind-key -n WheelUpPane if-shell -F "#{alternate_on}" "send-keys -M" "select-pane -t =; copy-mode -e; send-keys -M"
bind-key -n WheelDownPane if-shell -F "#{alternate_on}" "send-keys -M" "select-pane -t =; send-keys -M"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# < で左のウィンドウと入れ替え（連打可能）
bind-key -r < swap-window -t -1 \; select-window -t -1
# > で右のウィンドウと入れ替え（連打可能）
bind-key -r > swap-window -t +1 \; select-window -t +1


setw -g mode-keys vi

set -s set-clipboard on
set -s copy-command 'xsel -i'
bind-key -n MouseDown2Pane run-shell "xsel -o | tmux load-buffer - && tmux paste-buffer"
